# -*- coding: utf-8 -*-
"""IMU_random_data.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18LihV4x2vz1ZR2plYyGAhUhFDyQHkWFk
"""

import numpy as np
import pandas as pd

# Set the seed so that the numbers can be reproduced.
np.random.seed(0)  

df = pd.DataFrame(np.random.randn(5, 3), columns=['Gyroscope','Accelerometer','Momentum'])

df

df.to_csv('example.csv', index=False)

df.to_csv('example.csv', index=True)  # Or just leave off the index param; default is True

df.to_csv('example.csv', index=False, header=False)

df.to_csv('example.csv', index=False, header=False, sep='\t')